# 分類したい画像が格納されているディレクトリ
dir = "C:/Users/YourUser/Pictures/Unsorted"

# キーと分類先ディレクトリのマッピング
[dests]
# "a"キーを押すと"hoge/huga"に移動
"a" = "hoge/huga"
# "b"キーを押すと "./temp" に移動
"b" = "./temp"
# 移動先に"skip"を指定すると移動せずにスキップします
"s" = "skip"
# "q"キーは終了キーと被るので設定しないでください
# "q" = "not work"
